# Generated by Django 2.2.24 on 2021-12-01 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('seen', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('userDst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dest', to='user.User')),
                ('userSrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_src', to='user.User')),
            ],
        ),
    ]
